sudo: required

language: node_js

node_js:
    - "10"

git:
    submodules: true

before_install:
    - npm install -g @angular/cli

install:
    - npm i
    - ng build --prod
    - sudo curl  -L http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 -o /usr/bin/upx
    - sudo chmod +x /usr/bin/upx
    - cd ./dist
    - upx login angular-material-web "$NG" "$UPYUN"
    - upx sync ./ /
#     - upx rm -a /
#     - sleep(30)
#     - upx put ./   /
script:
    - cd ../
    - npm run test
